---
title: "02-data-project"
author: "Kurt Ingeman"
date: "9/20/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

This is going to be a chunk of code

```{r include=FALSE}

library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
library(gt)
library(kableExtra)

```



# read in data and merge with spp list 
```{r}

df <- read.csv(here("Data", "Marianas_fishabund_numperm2_sector.csv")) %>% 
  rename(SECTOR = ANALYSIS_SEC)

sum(df$N) # 1217 surveys

# remove standard error columns for reshape
df_wide <- df %>% 
  select(!contains("_SE")) 

# reshape data 
df_long <- df_wide %>% 
  pivot_longer(cols = 8:500, names_to ="SPECIES", values_to = "DENSITY") %>% 
  filter(DENSITY > 0)

# How many surveys?
length(unique(df_long$SPECIES)) #471

# read in species list
spp <- read.csv(here("Data", "FISH_SPECIES_04-21-2020.csv")) %>% 
  select(SPECIES, TAXONNAME, FAMILY, TROPHIC, TROPHIC_SIMPLE, TROPHIC_MONREP)

# merge with species list to incorporate trophic groups 
df_long <-  left_join(df_long, spp, by = "SPECIES") %>% 
  select(-X)




```

# data summaries
```{r}

richness_by_yr <- df_long %>% 
  group_by(ANALYSIS_YEAR) %>% 
  summarise(RICHNESS = length(unique(SPECIES)))

richness_by_yr %>% gt() %>%
  tab_header(
    title = "Species Richness",
    subtitle = "By Year")

surveys_by_year <- df_long %>% 
  group_by(ANALYSIS_YEAR, SECTOR) %>% 
  summarise(N = N) %>% 
  slice(1) %>% 
  group_by(ANALYSIS_YEAR) %>% 
  summarise(ANNUAL_SURVEYS = sum(N)) 

richness_surveys_year <- left_join(richness_by_yr, surveys_by_year, by = "ANALYSIS_YEAR") %>% 
  group_by(ANALYSIS_YEAR) %>% 
  mutate(spp_per_survey = RICHNESS / ANNUAL_SURVEYS)

richness_surveys_year %>%
  kbl() %>%
  kable_classic_2(full_width = F)

```
###

```{r}

df_long <- left_join(df_long, richness_surveys_year, by = "ANALYSIS_YEAR")

richness_sector <- df_long %>% 
  group_by(ANALYSIS_YEAR, SECTOR) %>% 
  mutate(SURVEYS = N, 
         RICHNESS = length(unique(SPECIES)), 
         RICH_DENSE = RICHNESS / SURVEYS) %>% 
  slice(1) %>% 
  select(SECTOR, ANALYSIS_YEAR, SURVEYS, RICHNESS, RICH_DENSE) %>% 
  arrange(ANALYSIS_YEAR, desc(RICH_DENSE))

richness_sector %>% 
  gt(groupname_col = "SECTOR") %>% 
  tab_header(
    title = "Fish Species Richness",
    subtitle = "By Year in each sector")

  
```


# data visulization
```{r}

ggplot(data = richness_sector, aes(x = RICHNESS, y = SURVEYS)) +
  geom_point() +
  geom_smooth(method = "lm")

```


```{r}
ggplot(data = richness_sector, aes(x = RICHNESS, y = SURVEYS, color = factor(ANALYSIS_YEAR))) +
  geom_point() +
  geom_smooth(method = "lm")
```

# data calculations
```{r}

df_troph <- df_long %>% 
  group_by(ANALYSIS_YEAR, SECTOR, TROPHIC_MONREP) %>% 
  mutate(TROPHIC_DENSE = sum(DENSITY)) %>% 
  mutate(YEAR = factor(ANALYSIS_YEAR), 
         SECTOR = factor(SECTOR)) %>% 
  ungroup()


ggplot(df_troph, aes(x = TROPHIC_MONREP, y = TROPHIC_DENSE)) +
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 45, hjust=1))
  

```

### Facet by year and by sector 
```{r}
  

 ggplot(df_troph, aes(x = TROPHIC_MONREP, y = TROPHIC_DENSE)) +
  geom_bar(stat = "identity") + 
  facet_grid( vars(YEAR), vars(SECTOR)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) 
```


```{r}
library(kableExtra)
dt <- mtcars[1:5, 1:6]

dt %>%
  kbl() %>%
  kable_styling()

dt %>%
  kbl() %>%
  kable_classic_2(full_width = F)

dt %>%
  kbl() %>%
  kable_paper("hover", full_width = F)


```













